### ISSUE TITLE
Add a picture that provides an abstract view of the programming model (with spaces, repositories, nodes, etc.)

### ISSUE THREAD

**Issue by albertolluch** [pSpaces/Programming-with-Spaces#1]

**Comment by albertolluch** [comment]
@michele-loreti @luhac @sequenze can you please check the picture and the description of spaces, repositories and gates that I added here:

https://github.com/pSpaces/Programming-with-Spaces/blob/master/guide.md#space-repositories-and-space-gates

From "To make a space..." until "As an example..."

**Comment by ghost** [comment]
This is now discussed by #4 and can be closed.
