### ISSUE TITLE
Tuple class/interface or not?

### ISSUE THREAD

**Issue by albertolluch** [pSpaces/Programming-with-Spaces#11]
As far as I can see the core API (`put`, `get`,...) of jSpace and dotSpace uses (1) built-in tuples/lists/variadic-argumetns to represent tuples, whereas dotSpace uses (2) an ad-hoc interface (`ITuple`). 

I see advantages in both options:

(1) One less new feature to learn (for the sake of minimality of the API). 
(2) Tuple is a main concept, it deserves a first-class treatment. 

It would be nice to have uniformity, but after all we are dealing with multiple languages and some non-uniformity will always be there. I have a slight preference for (1).

@michele-loreti @sequenze @luhac Opinions?

**Comment by sequenze** [comment]
a) I prefer having both. 
Usually i use the variadic arguments for creating and inserting (new) tuples, while the single object argument (ITuple) is for inserting already known tuples.

b)
However, as i mentioned in our previous conversation i am not entirely sure about the return value.
jSpace uses an object array for get / query, opposed to dotSpace that returns an Tuple instance.
The latter, for me at least, seems like its more true to the OOP paradigm.

**Comment by michele-loreti** [comment]
A tuple, by definition, must be an immutable sequence of immutable values. Any language can implement this behaviour in different way.

**Comment by albertolluch** [comment]
Given @michele-loreti I would say that we don't need a convention on this: whether to use a class `Tuple` or any other datatype that provides the expected behaviour is fine. Closing this issue...
