### ISSUE TITLE
FifoSpace in Programming with spaces/hello.md

### ISSUE THREAD

**Issue by sequenze** [pSpaces/Programming-with-Spaces#16]
@albertolluch 
```
C#
FifoSpace inbox = new FifoSpace();
```

Should be corrected to reflect the API.

**Comment by albertolluch** [comment]
done, but can I/you modify the C# example: dtu > inbox (as in the rest of the languages)

**Comment by sequenze** [comment]
Sure, I will do this later this evening :)
