### ISSUE TITLE
Discuss and describe the API related to repositories, spaces and gates

### ISSUE THREAD

**Issue by albertolluch** [pSpaces/Programming-with-Spaces#4]

**Comment by albertolluch** [comment]
@michele-loreti @luhac @sequenze can you please check API for space repositories that that I have included here:

https://github.com/pSpaces/Programming-with-Spaces/blob/master/guide.md#space-repositories-and-space-gates

From "Space repositories" until "As an example..."

**Comment by albertolluch** [comment]
@michele-loreti @sequenze 

Can a repository be "exposed" with two different names? In other words, is this allowed?

```
SpaceRepository repository = new SpaceRepository();
space = new SequentialSpace();
repository.add("name1", space);
repository.add("name2", space);
```

**Comment by sequenze** [comment]
> Can a repository be "exposed" with two different names? In other words, is this allowed?

I believe so yes. I haven't tested this, but I do not see anything that should prevent this.

**Comment by albertolluch** [comment]
Note that I have added a method to the repository API: `delSpace`. We have to decide what is the behaviour of
```
respository.delSpace("name1");
```
in the above example. Is the space removed from the repository or just the alias "name1" (so that the repository is still available as "name2")?

**Comment by sequenze** [comment]
> `Note that I have added a method to the repository API: delSpace. We have to decide what is the behaviour of
> 
> respository.delSpace("name1");
> 
> in the above example. Is the space removed from the repository or just the alias "name1" (so that the repository is still available as "name2")?`

In my opinion: Lets just remove the alias.... the space is gone once all alias' have been removed.

**Comment by albertolluch** [comment]
> Lets just remove the alias.... the space is gone once all alias' have been removed.

Thanks. I have updated the documentation accordingly.

**Comment by albertolluch** [comment]
I have discussed this with @michele-loreti and we all agree on the current specification. Closing this issue...
