### ISSUE TITLE
Hello World in C#

### ISSUE THREAD

**Issue by albertolluch** [pSpaces/Programming-with-Spaces#7]
@sequenze can you please check the C# code in 

https://github.com/pSpaces/Programming-with-Spaces/blob/master/hello.md

and create the example file?

**Comment by sequenze** [comment]
> @sequenze can you please check the C# code in

**1)**
```
C#
FifoSpace dtu = new SequentialSpace(); <---- This is not correct. 
```

For instantiation it should be:
ISpace dtu = new FifoSpace();  or FifoSpace dtu = new FifoSpace();  or SpaceBase dtu = new FifoSpace();

However, the section is called : **"Create a space named inbox at port 8080"** 
This leads one to think about networks when referring to ports.

If this is true, then the example should be using something similar to this:
```
SpaceRepository repository = new SpaceRepository();
repository.AddGate("tcp://127.0.0.1:123?CONN"); 
repository.AddSpace("dtu", new FifoSpace());
```

**2)**
```
C#
ITuple message = inbox.Get(typeof(string));

```

While not incorrect, the tuple space datastructure is named inbox, whereas the previous examples lists the name as 'dtu'.
I think that a consistent naming would be better.


**3) and create the example file?**

I don't quite follow you?

**Comment by albertolluch** [comment]
Fixed (still using FifoSpace until we agree on the final names). I removed the port thing. Let's keep it minimal (local spaces).

Regarding (3) I mean if you can ask the entire example as we have done for Java, see:

https://github.com/pSpaces/jSpace/blob/master/examples/HelloWorld/src/main/java/org/jspace/examples/helloworld/HelloWorld.java

**Comment by sequenze** [comment]
> Regarding (3) I mean if you can ask the entire example as we have done for Java, see:

There already exists an example in the section "Testing the setup":
https://github.com/pSpaces/dotSpace/wiki/getting-started

But you want a separate project for hello world?

**Comment by sequenze** [comment]
Should i scrap the dotSpace wiki pages and the technical documentation?

**Comment by albertolluch** [comment]
A simple separate project for the hello world is enough.

Don't scrap anything, I am actually using it to understand how dotSpaces works :)

**Comment by sequenze** [comment]
> Don't scrap anything, I am actually using it to understand how dotSpaces works :)

Okay. I meant to ask you if you wanted to keep the concept of custom tuples?

https://github.com/pSpaces/dotSpace/wiki/ITupleFactory-Interface

I mean, we can trim dotSpace if you want to?

**Comment by albertolluch** [comment]
Don't trim it.

I am opening another thread on this topic.

**Comment by albertolluch** [comment]
moved into dotSpace issues...
